language: node_js
node_js:
  - node
  - lts/*

arch:
  - amd64
  - ppc64le
  - s390x
  - arm64

os: linux  # different CPU architectures are only supported on Linux

env:
  - SKIP_BUILD=true

script:
  - npm run lint -- --no-fix
  - npm run build
