name: commit-lint

on:
  pull_request:

jobs:
  commit-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Commit lint
        # Dependabot sometimes makes some really long commit messages and I can't stop it
        continue-on-error: ${{ contains(github.event.pull_request.labels.*.name, 'dependencies') }}
        uses: ahmadnassri/action-conventional-commit-lint@v1.0.0
        with:
          token: ${{ github.token }}
